-- VibeCards Database Schema
-- Run this script in your Supabase SQL Editor to create the necessary tables

-- ============================================================================
-- DECKS TABLE
-- ============================================================================
-- Stores flashcard decks created by users
-- Each deck belongs to a user (identified by Clerk userId in owner_id)
CREATE TABLE IF NOT EXISTS decks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id TEXT NOT NULL,                    -- Clerk user ID (string)
  title TEXT NOT NULL,                       -- Deck title generated by AI
  topic TEXT NOT NULL,                       -- Original topic/notes provided by user
  cards JSONB NOT NULL,                      -- Array of cards: [{"front": "...", "back": "..."}, ...]
  created_at TIMESTAMPTZ DEFAULT NOW()       -- Timestamp when deck was created
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Index for efficient queries filtering by owner (used in dashboard)
CREATE INDEX IF NOT EXISTS idx_decks_owner_id ON decks(owner_id);

-- Index for sorting decks by creation date (newest first)
CREATE INDEX IF NOT EXISTS idx_decks_created_at ON decks(created_at DESC);

-- ============================================================================
-- NOTES
-- ============================================================================
-- 1. The cards column stores JSON in this format:
--    [
--      {"front": "Question or prompt", "back": "Answer or explanation"},
--      ...
--    ]
--
-- 2. owner_id uses TEXT to store Clerk user IDs (which are strings)
--
-- 3. All queries MUST filter by owner_id to ensure data isolation
--
-- 4. For additional security, see supabase/level2-rls.sql (optional RLS policies)
--    Note: RLS policies use Supabase Auth, not Clerk, so they won't work directly
--    with the current setup. Application-level filtering by owner_id is used instead.
